version: '2.0'

services:
    

    #time application service
   timeapp:
     image: abrahem17/myapp1
     environment:
      - GITURL=https://github.com/AbrahemGh1/example2.git
      - APPNAME=timeApp.jar
    
     volumes:
        # Pass volume named mysql-data to mysql container
      - C:\Users\Abrahim\Desktop\logfile.txt:/application/logfile.txt 
     ports:
      - 8080:8080
  


  #weather application service
   weatherapp:
     image: abrahem17/myapp1
     environment:
      - GITURL=https://github.com/AbrahemGh1/example2.git
      - APPNAME=weatherApp.jar
     ports:
      - 8081:8080   
      

      